### ISSUE TITLE
ModuleNotFoundError: No module named 'docker'

### ISSUE THREAD

**Issue by HassnaIrzan** [luiscarlosgph/docker-templates#7]
After running the command python3 -m dockerx.run --name vscode --image vscode:latest --nvidia 1 --command 'sleep infinity'. I get "ModuleNotFoundError: No module named 'docker'" error.

**Comment by luiscarlosgph** [comment]
Hi Hassna,

The setup.py of the package `dockerx` has the package `docker` as a dependency (so the package docker should be installed in your system). It looks to me as if you installed `dockerx`, and then removed docker-py from your system. Reinstalling `dockerx` should fix that problem:

```
$ pip uninstall dockerx
$ pip install dockerx
```

Kind regards,
Luis.

**Comment by HassnaIrzan** [comment]
Thanks, it works.
